force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>to store the student record</description>
    <label>Student</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>StudentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <defaultValue>&quot;ram&quot;</defaultValue>
    <description>for student</description>
    <inlineHelpText>Please add student name</inlineHelpText>
    <label>Student Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/soslEx.cls
public class soslEx {
    
    public static void myMethod(){
        
        List<list<sObject>> slist = [Find 'R?han' In All Fields Returning Account(Name,NumberofEmployees),Student__c(Name,Age__c,Student_Name__c)];
        system.debug(slist);
        
        for(sObject a :slist[1]){
            
            system.debug(a.get('Student_Name__c'));
            system.debug(a.get('Age__c'));
            
            
        }
        
    }

}